---
platform: windows

inputs:
- name: ci
- name: hydrator
  path: src/code.cloudfoundry.org/hydrator

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/test-hydrator-windows/run.ps1

params:
  NODES: 1
