---
platform: windows

inputs:
- name: ci
- name: winc
  path: src/code.cloudfoundry.org/winc

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/test-winc/run.ps1

params:
  TEST_CONTAINER_IMAGE_TAG:
  WINC_TEST_PERF_CONCURRENT_CONTAINERS: 15
