---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ruby-bosh-cli}}

inputs:
  - name: garden-windows-bosh-artifacts
  - name: release
  - name: ci

outputs:
  - name: release-output

run:
  path: ci/tasks/update-garden-windows-blobs/run
