---
platform: linux

image_resource: {type: docker-image, source: {repository: cloudfoundry/garden-windows-ci}}

inputs:
- name: ci
- name: windows2016fs-release

run:
  path: ci/tasks/update-windows2016fs-blob/run

outputs:
- name: windows2016fs-release-updated-blob
