---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
- name: ci
- name: windows2016fs-release
- name: create-timestamp
- name: sha

run:
  path: ci/tasks/create-fs-release-linux/run

params:
  DEV_ENV:
