---
platform: linux

image_resource: {type: docker-image, source: {repository: cloudfoundry/garden-windows-ci}}

inputs:
- name: ci
- name: repo

run:
  path: ci/tasks/ginkgo-from-gopath-linux/run

params:
  GOPATH: "repo"
  TEST_PATH: "repo"
  IGNORE_PACKAGES:
