---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: ci

outputs:
 - name: output

run:
  path: ci/tasks/get-gcs-file/run

params:
  BUCKET:
  FILE_NAME:
  SERVICE_ACCOUNT_KEY:
