---
platform: windows

inputs:
- name: ci
- name: winc-binary
- name: winc-network-binary
- name: groot-binary
- name: nstar-binary
- name: garden-runc-release
- name: windows2016fs
  path: src/code.cloudfoundry.org/windows2016fs

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/run-local-gats/run.ps1

params:
  WINC_TEST_ROOTFS:
