groups: []

resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: stemcell-builder
  type: git
  source:
    branch: develop
    # branch: master
    uri: git@github.com:cloudfoundry-incubator/bosh-windows-stemcell-builder.git
    private_key: ((CLOUDFOUNDRYINCUBATOR_BOSH_WINDOWS_STEMCELL_BUILDER_DEPLOY_KEY))
- name: windows-stemcell-dependencies
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/windows-stemcell-dependencies.git
    private_key: ((PIVOTAL-CF_WINDOWS-STEMCELL-DEPENDENCIES_PRIVATE_KEY))
- name: openssh-release
  type: github-release
  source:
    user: PowerShell
    repository: Win32-OpenSSH
    access_token: ((GREENHOUSE_CI_ACCESS_TOKEN))
- name: stemcells-main-version
  type: semver
  source:
    bucket: bosh-windows-stemcells
    key: versions/stemcells-main-version-edge
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
    initial_version: 1200.0.0
- name: vsphere-stemcell-version
  type: semver
  source:
    bucket: bosh-windows-stemcells
    key: versions/vsphere-stemcell-version-edge
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
    initial_version: 1200.0.0

jobs:
- name: create-vsphere-stemcell-from-diff
  serial: true
  serial_groups: [vsphere]
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere-windows]
    - get: version
      tags: [vsphere-windows]
      # passed: [build-stemcells]
      resource: vsphere-stemcell-version
      trigger: true
    - get: stemcell-builder
      # passed: [build-stemcells]
      tags: [vsphere-windows]
    - get: windows-stemcell-dependencies
      tags: [vsphere-windows]
    - get: stemcells-main-version
      # passed: [build-stemcells]
    - get: sshd
      resource: openssh-release
      version: { tag: 'v0.0.18.0' }
  # - put: version
  #   resource: vsphere-stemcell-version
  #   params:
  #     pre: build
  - task: create-stemcell
    privileged: true
    file: ci/bosh-windows-stemcell-builder/create-vsphere-stemcell-from-diff/task.yml
    tags: [dev-windows-worker]
    # tags: [diffcell-windows-worker]
    params:
      ADMINISTRATOR_PASSWORD: "Password123!"
      OS_VERSION: windows2012R2
      PRODUCT_KEY: D2N9P-3P6X9-2R39C-7RTCD-MDVJX
      ORGANIZATION: Pivotal
      OWNER: Pivotal
      STEMCELL_DEPS_DIR: ../windows-stemcell-dependencies
      AWS_ACCESS_KEY_ID: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
      AWS_SECRET_ACCESS_KEY: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
      AWS_REGION: us-east-1
      VHD_VMDK_BUCKET: bosh-windows-diffcell
      DIFF_OUTPUT_BUCKET: dev-bosh-windows-diffcell
      # DIFF_OUTPUT_BUCKET: bosh-windows-diffcell
      STEMCELL_OUTPUT_BUCKET: "dev-bosh-windows-stemcells-pre-release-candidate"
      # STEMCELL_OUTPUT_BUCKET: "bosh-windows-stemcells-pre-release-candidate"
      CACHE_DIR: "C:\\image-data"
