# use master branch of stemcell builder
- type: replace
  path: /resources/name=stemcell-builder/source/branch
  value: master

# bump vsphere-stemcell-version
- type: replace
  path: /jobs/name=create-vsphere-stemcell-from-diff/plan/0/aggregate/-
  value:
    put: version
    resource: vsphere-stemcell-version
    params:
      pre: build

# use production diffcell worker
- type: replace
  path: /jobs/name=create-vsphere-stemcell-from-diff/plan/task=create-stemcell/tags
  value: [diffcell-windows-worker]

# use production s3 buckets
- type: replace
  path: /jobs/name=create-vsphere-stemcell-from-diff/plan/task=create-stemcell/params/DIFF_OUTPUT_BUCKET
  value: bosh-windows-diffcell
- type: replace
  path: /jobs/name=create-vsphere-stemcell-from-diff/plan/task=create-stemcell/params/STEMCELL_OUTPUT_BUCKET
  value: bosh-windows-stemcells-pre-release-candidate

