---
platform: linux

image_resource: {type: docker-image, source: {repository: cloudfoundry/garden-windows-ci}}

inputs:
- name: ci
- name: hydrator
  path: src/code.cloudfoundry.org/hydrator

run:
  path: ci/tasks/test-hydrator-linux/run

params:
  IGNORE_PACKAGES:
