---
name: windows2016fs-online-test

releases:
- name: windows2016fs
  version: latest

stemcells:
- alias: windows
  os: windows2016
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000-300000
  max_errors: 2
  max_in_flight: 1
  serial: false
  update_watch_time: 30000-300000

instance_groups:
- azs:
  - z1
  name: windows2016fs
  instances: 1
  jobs:
  - name: windows2016fs
    release: windows2016fs
  networks:
  - name: default
    default:
    - dns
    - gateway
  stemcell: windows
  vm_extensions:
  - 100GB_ephemeral_disk
  vm_type: m3.large
