---
platform: windows

inputs:
- name: ci
- name: hwc
  path: src/code.cloudfoundry.org/hwc

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/test-hwc/run.ps1
