groups:
- name: all
  jobs:
  - baboon-deploy-cf
  - baboon-destroy-cf
  - sudbury-deploy-cf
  - sudbury-destroy-cf

resources:
- name: cf-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git
    tag_filter: v*
- name: greenhouse-private
  type: git
  source:
    branch: master
    private_key: {{GREENHOUSE_CI_GITHUB_PRIVATE_KEY}}
    uri: git@github.com:pivotal-cf/greenhouse-private
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: gcp-windows-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells-release-candidates
    regexp: light-bosh-stemcell-(.*)-google-kvm-windows2012R2-go_agent.tgz
- name: vsphere-windows-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells-private-release-candidates
    regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: gcp-linux-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent
- name: vsphere-linux-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
- name: wats
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/wats.git
- name: weekly-trigger
  type: time
  source:
    days: [Saturday]
    location: US/Eastern
    start: 12:00 AM
    stop: 1:00 AM
- name: baboon-lock-pool
  type: pool
  source:
    branch: master
    pool: baboon
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks
- name: sudbury-lock-pool
  type: pool
  source:
    branch: master
    pool: sudbury
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

jobs:
- name: baboon-destroy-cf
  serial: true
  plan:
  - put: baboon-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: ci
      - get: weekly-trigger
        trigger: true
    - task: destroy-cf
      file: ci/bosh-deld/task.yml
      params:
        BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
    ensure:
      put: baboon-lock-pool
      params:
        release: baboon-lock-pool

- name: baboon-deploy-cf
  serial: true
  plan:
  - put: baboon-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: cf-deployment
      - get: greenhouse-private
      - get: ci
      - get: gcp-windows-stemcell
        trigger: true
      - get: gcp-linux-stemcell
      - get: wats
      - get: weekly-trigger
        trigger: true
        passed: [baboon-destroy-cf]
    - aggregate:
      - task: upload-linux-stemcell
        file: ci/bosh-us/task.yml
        input_mapping: {stemcell: gcp-linux-stemcell}
        params:
          BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
          BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
          BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
          BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
      - task: upload-windows-stemcell
        file: ci/bosh-us/task.yml
        input_mapping: {stemcell: gcp-windows-stemcell}
        params:
          BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
          BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
          BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
          BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
    - task: deploy-cf
      file: ci/deploy-cf/task.yml
      params:
        ENVIRONMENT: baboon
        BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
        CF_DOMAIN: baboon.cf-app.com
    - put: greenhouse-private
      params:
        repository: output/greenhouse-private
        rebase: true
    - task: clean-up
      file: ci/bosh-cleanup/task.yml
      params:
        BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
    - task: wats
      file: ci/run-wats/task.yml
      params:
        ADMIN_PASSWORD: {{BABOON_ADMIN_PASSWORD}}
        ADMIN_USER: admin
        API: api.baboon.cf-app.com
        APPS_DOMAIN: baboon.cf-app.com
        NUM_WIN_CELLS: 1
        SOCKET_ADDRESS_FOR_SECURITY_GROUP_TEST: 10.0.0.6:25555
    ensure:
      put: baboon-lock-pool
      params:
        release: baboon-lock-pool

- name: sudbury-destroy-cf
  serial: true
  plan:
  - put: sudbury-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: ci
    - task: destroy-cf
      file: ci/bosh-deld/task.yml
      tags: [vsphere]
      params:
        BOSH_CLIENT: admin
        BOSH_CLIENT_SECRET: {{sudbury_client_secret}}
        BOSH_ENVIRONMENT: {{sudbury_environment}}
        BOSH_CA_CERT: {{sudbury_ca_cert}}
    ensure:
      put: sudbury-lock-pool
      params:
        release: sudbury-lock-pool

- name: sudbury-deploy-cf
  serial: true
  plan:
  - put: sudbury-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: cf-deployment
      - get: greenhouse-private
      - get: ci
      - get: vsphere-windows-stemcell
        tags: [vsphere]
      - get: vsphere-linux-stemcell
        tags: [vsphere]
      - get: wats
    - aggregate:
      - task: upload-linux-stemcell
        file: ci/bosh-us/task.yml
        input_mapping: {stemcell: vsphere-linux-stemcell}
        tags: [vsphere]
        params:
          BOSH_CLIENT: admin
          BOSH_CLIENT_SECRET: {{sudbury_client_secret}}
          BOSH_ENVIRONMENT: {{sudbury_environment}}
          BOSH_CA_CERT: {{sudbury_ca_cert}}
      - task: upload-windows-stemcell
        file: ci/bosh-us/task.yml
        input_mapping: {stemcell: vsphere-windows-stemcell}
        tags: [vsphere]
        params:
          BOSH_CLIENT: admin
          BOSH_CLIENT_SECRET: {{sudbury_client_secret}}
          BOSH_ENVIRONMENT: {{sudbury_environment}}
          BOSH_CA_CERT: {{sudbury_ca_cert}}
    - task: deploy-cf
      tags: [vsphere]
      file: ci/deploy-cf/task.yml
      params:
        ENVIRONMENT: sudbury
        BOSH_CLIENT: admin
        BOSH_CLIENT_SECRET: {{sudbury_client_secret}}
        BOSH_ENVIRONMENT: {{sudbury_environment}}
        BOSH_CA_CERT: {{sudbury_ca_cert}}
        CF_DOMAIN: sudbury.cf-app.com
    - put: greenhouse-private
      params:
        repository: output/greenhouse-private
        rebase: true
    - task: clean-up
      file: ci/bosh-cleanup/task.yml
      tags: [vsphere]
      params:
        BOSH_CLIENT: admin
        BOSH_CLIENT_SECRET: {{sudbury_client_secret}}
        BOSH_ENVIRONMENT: {{sudbury_environment}}
        BOSH_CA_CERT: {{sudbury_ca_cert}}
    - task: wats
      tags: [vsphere]
      file: ci/run-wats/task.yml
      params:
        ADMIN_PASSWORD: {{sudbury_cf_admin_password}}
        ADMIN_USER: admin
        API: api.sudbury.cf-app.com
        APPS_DOMAIN: sudbury.cf-app.com
        NUM_WIN_CELLS: 1
        SOCKET_ADDRESS_FOR_SECURITY_GROUP_TEST: 10.74.41.6:25555
    ensure:
      put: sudbury-lock-pool
      params:
        release: sudbury-lock-pool
