resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: cf-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git
    tag_filter: v*
- name: winc-release-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry-incubator/winc-release.git
- name: windows2016fs-release-insider
  type: git
  source:
    branch: insider-10.0.16278.1000
    uri: https://github.com/cloudfoundry-incubator/windows2016fs-release.git
- name: vsphere-windows2012R2-stemcell
  type: s3
  source:
   bucket: bosh-windows-stemcells-private
   regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
   access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
   secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
- name: vsphere-windows2016-stemcell
  type: s3
  source:
   bucket: vsphere-stemcell-pre-release-candidate-vmx-2016-insider
   regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2016-go_agent.tgz
   access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
   secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
- name: mulgore-cf-deployment
  type: bosh-deployment
  source:
    deployment: cf
    client: {{MULGORE_BOSH_CLIENT}}
    client_secret: {{MULGORE_BOSH_CLIENT_SECRET}}
    ca_cert: {{MULGORE_BOSH_CA_CERT}}
    target: {{MULGORE_BOSH_ENVIRONMENT}}
    vars_store:
      provider: gcs
      config:
        bucket: mulgore
        file_name: cf/creds.yml
        json_key: {{SPITFIRE_SERVICE_ACCOUNT_JSON}}
- name: garden-windows-private
  type: git
  source:
    branch: master
    private_key: {{GARDEN_WINDOWS_CI_GITHUB_PRIVATE_KEY}}
    uri: git@github.com:pivotal-cf/garden-windows-private
- name: cfbench
  type: git
  source:
    branch: longrunning-pipeline
    uri: https://github.com/greenhouse-org/cfbench.git
- name: every-5mins
  type: time
  source:
    interval: 5m
- name: every-1min
  type: time
  source:
    interval: 1m

jobs:
- name: mulgore-deploy-cf
  serial: true
  serial_groups:
  - cfbench-windows2016
  - cfbench-windows2012R2
  - cfbench-cflinuxfs2
  - longrunning-windows2016
  - longrunning-windows2012R2
  - longrunning-cflinuxfs2
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: cf-deployment
      trigger: true
      tags: [vsphere]
    - get: vsphere-windows2012R2-stemcell
      tags: [vsphere]
    - get: vsphere-windows2016-stemcell
      tags: [vsphere]
    - get: garden-windows-private
      tags: [vsphere]
    - get: winc-release-develop
      trigger: true
      tags: [vsphere]
    - get: windows2016fs-release-insider
      trigger: true
      tags: [vsphere]
  - aggregate:
    - task: get-linux-stemcell
      file: ci/get-vsphere-linux-stemcell/task.yml
      output_mapping: { stemcell: vsphere-linux-stemcell }
      tags: [vsphere]
    - task: get-cf-vars
      file: ci/get-gcs-file/task.yml
      output_mapping: { output: cf-vars }
      params:
        BUCKET: mulgore
        FILE_NAME: cf/vars.yml
        SERVICE_ACCOUNT_KEY: {{SPITFIRE_SERVICE_ACCOUNT_JSON}}
      tags: [vsphere]
    - task: create-winc-release
      file: ci/bosh-cr/task.yml
      input_mapping:
        release: winc-release-develop
      output_mapping:
        release-tarball: winc-tarball
      tags: [vsphere]
    - task: upload-windows2016fs-release
      file: ci/upload-windows2016fs-release/task.yml
      input_mapping: { windows2016fs-release: windows2016fs-release-insider }
      params:
        BOSH_CA_CERT: {{MULGORE_BOSH_CA_CERT}}
        BOSH_CLIENT: {{MULGORE_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{MULGORE_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{MULGORE_BOSH_ENVIRONMENT}}
      tags: [vsphere]
  - put: mulgore-cf-deployment
    params:
      manifest: cf-deployment/cf-deployment.yml
      stemcells:
      - vsphere-linux-stemcell/*.tgz
      - vsphere-windows2012R2-stemcell/*.tgz
      - vsphere-windows2016-stemcell/*.tgz
      releases:
      - winc-tarball/*.tgz
      ops_files:
      - cf-deployment/operations/scale-to-one-az.yml
      - cf-deployment/operations/windows-cell.yml
      - cf-deployment/operations/use-latest-windows-stemcell.yml
      - cf-deployment/operations/experimental/windows2016-cell.yml
      - cf-deployment/operations/experimental/use-latest-windows2016-stemcell.yml
      - cf-deployment/operations/experimental/use-bosh-dns.yml
      - cf-deployment/operations/experimental/use-bosh-dns-for-containers.yml
      - garden-windows-private/operations-common/windows2016-prs.yml
      - garden-windows-private/operations-common/windows2016-insider-preview.yml
      - garden-windows-private/operations-common/latest-winc.yml
      - garden-windows-private/operations-common/downgrade-garden-runc.yml
      - garden-windows-private/operations-common/enable-bosh-ssh-windows.yml
      vars_files:
      - cf-vars/vars.yml
      cleanup: true
    get_params:
      skip_export: true
    tags: [vsphere]

- name: mulgore-cfbench-windows2016
  serial: true
  serial_groups:
  - cfbench-windows2016
  - serial-app-push
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: cfbench
      tags: [vsphere]
    - get: every-5mins
      trigger: true
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-deploy-cf]
      tags: [vsphere]
  - task: cfbench
    file: ci/cfbench/task.yml
    input_mapping: {app: ci}
    params:
      CF_API: api.mulgore.cf-app.com
      CF_STACK: windows2016
      CF_USERNAME: admin
      CF_PASSWORD: {{MULGORE_ADMIN_PASSWORD}}
      CF_ORG: cfbench
      CF_SPACE: windows2016
      CF_TAG: windows2016
      APP_DIR: app/test-webapp
      APP_BUILDPACK: binary_buildpack
      APP_START_COMMAND: ./webapp.exe
      DATADOG_API_KEY: {{DATADOG_API_KEY}}
      DATADOG_APPLICATION_KEY: {{DATADOG_APPLICATION_KEY}}
    tags: [vsphere]

- name: mulgore-push-longrunning-app-windows2016
  serial: true
  serial_groups:
  - longrunning-windows2016
  - serial-app-push
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-deploy-cf]
      tags: [vsphere]
  - task: push-app
    file: ci/push-app/task.yml
    input_mapping: {app: ci}
    params:
      CF_API: api.mulgore.cf-app.com
      CF_STACK: windows2016
      CF_USERNAME: admin
      CF_PASSWORD: {{MULGORE_ADMIN_PASSWORD}}
      CF_ORG: longrunning
      CF_SPACE: windows2016
      APP_DIR: app/test-webapp
      APP_START_COMMAND: ./webapp.exe
      APP_BUILDPACK: binary_buildpack
    tags: [vsphere]

- name: mulgore-curl-longrunning-app-windows2016
  serial: true
  serial_groups:
  - longrunning-windows2016
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: every-1min
      trigger: true
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-push-longrunning-app-windows2016]
      tags: [vsphere]
  - task: curl-app
    file: ci/curl-app/task.yml
    params:
      CF_APP_URL: longrunning-windows2016.mulgore.cf-app.com
      CF_TAG: windows2016
      DATADOG_API_KEY: {{DATADOG_API_KEY}}
      DATADOG_APPLICATION_KEY: {{DATADOG_APPLICATION_KEY}}
    tags: [vsphere]

- name: mulgore-cfbench-windows2012R2
  serial: true
  serial_groups:
  - cfbench-windows2012R2
  - serial-app-push
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: cfbench
      tags: [vsphere]
    - get: every-5mins
      trigger: true
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-deploy-cf]
      tags: [vsphere]
  - task: cfbench
    file: ci/cfbench/task.yml
    input_mapping: {app: ci}
    params:
      CF_API: api.mulgore.cf-app.com
      CF_STACK: windows2012R2
      CF_USERNAME: admin
      CF_PASSWORD: {{MULGORE_ADMIN_PASSWORD}}
      CF_ORG: cfbench
      CF_SPACE: windows2012R2
      CF_TAG: windows2012R2
      APP_DIR: app/test-webapp
      APP_BUILDPACK: binary_buildpack
      APP_START_COMMAND: ./webapp.exe
      DATADOG_API_KEY: {{DATADOG_API_KEY}}
      DATADOG_APPLICATION_KEY: {{DATADOG_APPLICATION_KEY}}
    tags: [vsphere]

- name: mulgore-push-longrunning-app-windows2012R2
  serial: true
  serial_groups:
  - longrunning-windows2012R2
  - serial-app-push
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-deploy-cf]
      tags: [vsphere]
  - task: push-app
    file: ci/push-app/task.yml
    input_mapping: {app: ci}
    params:
      CF_API: api.mulgore.cf-app.com
      CF_STACK: windows2012R2
      CF_USERNAME: admin
      CF_PASSWORD: {{MULGORE_ADMIN_PASSWORD}}
      CF_ORG: longrunning
      CF_SPACE: windows2012R2
      APP_DIR: app/test-webapp
      APP_START_COMMAND: ./webapp.exe
      APP_BUILDPACK: binary_buildpack
    tags: [vsphere]

- name: mulgore-curl-longrunning-app-windows2012R2
  serial: true
  serial_groups:
  - longrunning-windows2012R2
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: every-1min
      trigger: true
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-push-longrunning-app-windows2012R2]
      tags: [vsphere]
  - task: curl-app
    file: ci/curl-app/task.yml
    params:
      CF_APP_URL: longrunning-windows2012R2.mulgore.cf-app.com
      CF_TAG: windows2012R2
      DATADOG_API_KEY: {{DATADOG_API_KEY}}
      DATADOG_APPLICATION_KEY: {{DATADOG_APPLICATION_KEY}}
    tags: [vsphere]

- name: mulgore-cfbench-cflinuxfs2
  serial: true
  serial_groups:
  - cfbench-cflinuxfs2
  - serial-app-push
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: cfbench
      tags: [vsphere]
    - get: every-5mins
      trigger: true
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-deploy-cf]
      tags: [vsphere]
  - task: cfbench
    file: ci/cfbench/task.yml
    input_mapping: {app: ci}
    params:
      CF_API: api.mulgore.cf-app.com
      CF_STACK: cflinuxfs2
      CF_USERNAME: admin
      CF_PASSWORD: {{MULGORE_ADMIN_PASSWORD}}
      CF_ORG: cfbench
      CF_SPACE: cflinuxfs2
      CF_TAG: cflinuxfs2
      APP_DIR: app/test-webapp
      APP_BUILDPACK: binary_buildpack
      APP_START_COMMAND: ./webapp
      DATADOG_API_KEY: {{DATADOG_API_KEY}}
      DATADOG_APPLICATION_KEY: {{DATADOG_APPLICATION_KEY}}
    tags: [vsphere]

- name: mulgore-push-longrunning-app-cflinuxfs2
  serial: true
  serial_groups:
  - longrunning-cflinuxfs2
  - serial-app-push
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-deploy-cf]
      tags: [vsphere]
  - task: push-app
    file: ci/push-app/task.yml
    input_mapping: {app: ci}
    params:
      CF_API: api.mulgore.cf-app.com
      CF_STACK: cflinuxfs2
      CF_USERNAME: admin
      CF_PASSWORD: {{MULGORE_ADMIN_PASSWORD}}
      CF_ORG: longrunning
      CF_SPACE: cflinuxfs2
      APP_DIR: app/test-webapp
      APP_START_COMMAND: ./webapp
      APP_BUILDPACK: binary_buildpack
    tags: [vsphere]

- name: mulgore-curl-longrunning-app-cflinuxfs2
  serial: true
  serial_groups:
  - longrunning-cflinuxfs2
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: every-1min
      trigger: true
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-push-longrunning-app-cflinuxfs2]
      tags: [vsphere]
  - task: curl-app
    file: ci/curl-app/task.yml
    params:
      CF_APP_URL: longrunning-cflinuxfs2.mulgore.cf-app.com
      CF_TAG: cflinuxfs2
      DATADOG_API_KEY: {{DATADOG_API_KEY}}
      DATADOG_APPLICATION_KEY: {{DATADOG_APPLICATION_KEY}}
    tags: [vsphere]
