resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: cf-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git
    tag_filter: v*
- name: vsphere-windows2012R2-stemcell
  type: s3
  source:
   bucket: bosh-windows-stemcells-private
   regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
   access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
   secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
- name: mulgore-cf-deployment
  type: bosh-deployment
  source:
    deployment: cf
    client: {{MULGORE_BOSH_CLIENT}}
    client_secret: {{MULGORE_BOSH_CLIENT_SECRET}}
    ca_cert: {{MULGORE_BOSH_CA_CERT}}
    target: {{MULGORE_BOSH_ENVIRONMENT}}
    vars_store:
      provider: gcs
      config:
        bucket: mulgore
        file_name: cf/creds.yml
        json_key: {{SPITFIRE_SERVICE_ACCOUNT_JSON}}
- name: garden-windows-private
  type: git
  source:
    branch: use-windows-alias
    private_key: {{GARDEN_WINDOWS_CI_GITHUB_PRIVATE_KEY}}
    uri: git@github.com:pivotal-cf/garden-windows-private
- name: cfbench
  type: git
  source:
    branch: bypass-stager
    uri: https://github.com/greenhouse-org/cfbench.git
- name: wats
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/wats.git
- name: every-20mins
  type: time
  source:
    interval: 20m
- name: every-1min
  type: time
  source:
    interval: 1m

jobs:
- name: mulgore-deploy-cf
  serial: true
  serial_groups:
  - cfbench-windows2012R2
  - longrunning-windows2012R2
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: cf-deployment
      trigger: true
      tags: [vsphere]
    - get: vsphere-windows2012R2-stemcell
      tags: [vsphere]
    - get: garden-windows-private
      tags: [vsphere]
  - aggregate:
    - task: get-linux-stemcell
      file: ci/get-vsphere-linux-stemcell/task.yml
      output_mapping: { stemcell: vsphere-linux-stemcell }
      tags: [vsphere]
    - task: get-cf-vars
      file: ci/get-gcs-file/task.yml
      output_mapping: { output: cf-vars }
      params:
        BUCKET: mulgore
        FILE_NAME: cf/vars.yml
        SERVICE_ACCOUNT_KEY: {{SPITFIRE_SERVICE_ACCOUNT_JSON}}
      tags: [vsphere]
  - put: mulgore-cf-deployment
    params:
      manifest: cf-deployment/cf-deployment.yml
      stemcells:
      - vsphere-linux-stemcell/*.tgz
      - vsphere-windows2012R2-stemcell/*.tgz
      ops_files:
      - cf-deployment/operations/bypass-cc-bridge.yml
      - cf-deployment/operations/scale-to-one-az.yml
      - cf-deployment/operations/windows-cell.yml
      - garden-windows-private/operations-common/latest-windows2012R2-stemcell.yml
      vars_files:
      - cf-vars/vars.yml
      cleanup: true
    get_params:
      skip_export: true
    tags: [vsphere]

- name: mulgore-cfbench-windows2012R2
  serial: true
  serial_groups:
  - cfbench-windows2012R2
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: cfbench
      tags: [vsphere]
    - get: wats
      tags: [vsphere]
    - get: every-20mins
      trigger: true
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-deploy-cf]
      tags: [vsphere]
  - task: cfbench
    file: ci/cfbench/task.yml
    input_mapping: {app: wats}
    params:
      CF_API: api.mulgore.cf-app.com
      CF_STACK: windows2012R2
      CF_USERNAME: admin
      CF_PASSWORD: {{MULGORE_ADMIN_PASSWORD}}
      CF_ORG: cfbench
      CF_SPACE: windows2012R2
      CF_TAG: windows2012R2
      APP_DIR: app/assets/nora/NoraPublished
      DATADOG_API_KEY: {{DATADOG_API_KEY}}
      DATADOG_APPLICATION_KEY: {{DATADOG_APPLICATION_KEY}}
    tags: [vsphere]

- name: mulgore-push-longrunning-app-windows2012R2
  serial: true
  serial_groups:
  - longrunning-windows2012R2
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: wats
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-deploy-cf]
      tags: [vsphere]
  - task: push-app
    file: ci/push-app/task.yml
    input_mapping: {app: wats}
    params:
      CF_API: api.mulgore.cf-app.com
      CF_STACK: windows2012R2
      CF_USERNAME: admin
      CF_PASSWORD: {{MULGORE_ADMIN_PASSWORD}}
      CF_ORG: longrunning
      CF_SPACE: windows2012R2
      APP_DIR: app/assets/nora/NoraPublished
    tags: [vsphere]

- name: mulgore-curl-longrunning-app-windows2012R2
  serial: true
  serial_groups:
  - longrunning-windows2012R2
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: every-1min
      trigger: true
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-push-longrunning-app-windows2012R2]
      tags: [vsphere]
  - task: curl-app
    file: ci/curl-app/task.yml
    params:
      CF_APP_URL: longrunning-windows2012R2.mulgore.cf-app.com
      CF_TAG: windows2012R2
      DATADOG_API_KEY: {{DATADOG_API_KEY}}
      DATADOG_APPLICATION_KEY: {{DATADOG_APPLICATION_KEY}}
    tags: [vsphere]
