---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: windows-stemcell-dependencies
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/windows-stemcell-dependencies.git
    private_key: {{PIVOTAL-CF_WINDOWS-STEMCELL-DEPENDENCIES_PRIVATE_KEY}}
- name: updated-vmx-version
  type: semver
  source:
    bucket: private-windows-stemcells-semver
    initial_version: 1.0.0
    key: versions/updated-vmx-version
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
    initial_version: "1.0.0"
- name: stemcell-version
  type: semver
  source:
    bucket: {{private_windows_stemcells_semver}}
    key: versions/stemcell-version-private
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
    bucket: private-windows-stemcells-semver
    initial_version: 1079.0.0
- name: private-stemcell-pre-release-candidate
  type: s3
  source:
    bucket: {{private_windows_stemcells_production}}
    regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: private-stemcell-release-candidate
  type: s3
  source:
    bucket: {{private_windows_stemcells_release_candidate}}
    regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
    region_name: us-east-2
- name: stemcell-builder-released-sha
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: stemcell-(.*).json
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: pivnet-private-stemcells-release
  type: pivnet
  source:
    api_token: {{PIVNET_BOT_API_TOKEN}}
    product_slug: {{private_product_slug}}
    access_key_id: {{PIVNET_STEMCELL_WINDOWS_ACCESS_KEY_PRIVATE}}
    secret_access_key: {{PIVNET_STEMCELL_WINDOWS_SECRET_ACCESS_KEY_PRIVATE}}
- name: openssh-release
  type: github-release
  source:
    user: PowerShell
    repository: Win32-OpenSSH
    access_token: {{GREENHOUSE_CI_ACCESS_TOKEN}}

jobs:
- name: create-vsphere-add-updates
  serial: true
  serial_groups: [vsphere]
  plan:
  - aggregate:
    - get: ci
    - get: stemcell-builder-released-sha
    - get: windows-stemcell-dependencies
    - get: vmx-version
      resource: updated-vmx-version
  - task: checkout-stemcell-builder
    file: ci/bosh-windows-stemcell-builder/checkout-stemcell-builder/task.yml
  - task: add-updates
    privileged: true
    input_mapping:
      version: vmx-version
    tags:
     - private-windows-worker
    file: ci/bosh-windows-stemcell-builder/create-vmx-add-updates/task.yml
    params:
      ADMINISTRATOR_PASSWORD: {{ADMINISTRATOR_PASSWORD}}
      AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
      AWS_REGION: {{REGION}}
      INPUT_BUCKET: {{private_windows_stemcells_vmx}}
      OUTPUT_BUCKET: {{private_windows_stemcells_vmx}}
  - put: updated-vmx-version
    params: {bump: major}

- name: create-vsphere-stemcell
  serial: true
  serial_groups: [vsphere]
  plan:
  - aggregate:
    - get: ci
    - get: stemcell-builder-released-sha
      trigger: true
    - get: windows-stemcell-dependencies
    - get: version
      resource: stemcell-version
    - get: vmx-version
      resource: updated-vmx-version
      trigger: true
      passed: [create-vsphere-add-updates]
    - get: sshd
      tag: 'v0.0.18.0'
      resource: openssh-release
      version: { tag: 'v0.0.18.0' }
  - task: checkout-stemcell-builder
    file: ci/bosh-windows-stemcell-builder/checkout-stemcell-builder/task.yml
  - task: create-stemcell
    privileged: true
    file: ci/bosh-windows-stemcell-builder/create-vsphere-stemcell-from-vmx/task.yml
    params:
      ADMINISTRATOR_PASSWORD: {{ADMINISTRATOR_PASSWORD}}
      NEW_PASSWORD: {{STEMCELL_PASSWORD}}
      PRODUCT_KEY: {{PRODUCT_KEY}}
      ORGANIZATION: Pivotal
      OWNER: Pivotal
      AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
      AWS_REGION: {{REGION}}
      INPUT_BUCKET: {{private_windows_stemcells_vmx}}
      OUTPUT_BUCKET: {{private_windows_stemcells_production}}
      ENABLE_RDP: true
      ENABLE_KMS: true
      KMS_HOST: {{KMS_HOST}}
    tags:
    - private-windows-worker
  - put: stemcell-version
    params: {bump: patch}

- name: test-vsphere-stemcell
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: bosh-windows-stemcell
      resource: private-stemcell-pre-release-candidate
      trigger: true
    - get: stemcell-builder-released-sha
      passed: [create-vsphere-stemcell]
    - get: version
      resource: stemcell-version
      passed: [create-vsphere-stemcell]
  - task: checkout-stemcell-builder
    file: ci/bosh-windows-stemcell-builder/checkout-stemcell-builder/task.yml
  - task: test-stemcell
    file: ci/bosh-windows-stemcell-builder/bwats/task.yml
    attempts: 5
    params:
      VM_TYPE: large
      BOSH_CLIENT_SECRET: {{regina_client_secret}}
      BOSH_CLIENT: {{regina_client}}
      BOSH_TARGET: {{regina_environment}}
      BOSH_CA_CERT: {{regina_ca_cert}}
      STEMCELL_PATH: bosh-windows-stemcell/bosh-stemcell-*-vsphere-esxi-windows2012R2-go_agent.tgz
  - task: vsphere-set-stemcell-version
    file: ci/set-stemcell-version/task.yml
  - put: private-stemcell-release-candidate
    params:
      file: final-stemcell/bosh-stemcell-*-vsphere-esxi-windows2012R2-go_agent.tgz

- name: upload-internal-stemcells
  serial: true
  plan:
  - aggregate:
    - get: private-stemcell-release-candidate
      passed: [test-vsphere-stemcell]
    - get: stemcell-version
      passed: [test-vsphere-stemcell]
  - task: pivnet-metadata
    config:
      inputs: [{name: private-stemcell-release-candidate}]
      outputs: [{name: pivnet-metadata}]
      platform: linux
      image_resource: {type: docker-image, source: {repository: concourse/git-resource } }
      run:
        path: bash
        args:
        - -c
        - |
          cat > pivnet-metadata/metadata <<EOF
          ---
          release:
            version: "$(cat private-stemcell-release-candidate/version)"
            release_type: Beta Release
            eula_slug: "pivotal_beta_eula"
            availability: Admins Only
            user_group_ids: []
            eccn: ""
            license_exception: ""
          product_files:
          - file: $(ls private-stemcell-release-candidate/*.tgz)
            upload_as: "vSphere Stemcell for Windows 2012R2 Server"
          EOF
  - put: pivnet-private-stemcells-release
    params:
      file_glob: private-stemcell-release-candidate/*.tgz
      s3_filepath_prefix: {{PIVNET_STEMCELL_WINDOWS_PRIVATE_FILEPATH_PREFIX}}
      metadata_file: pivnet-metadata/metadata
  - put: stemcell-version
    params: {bump: minor}
