resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: winc-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry-incubator/winc.git
- name: winc-master
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry-incubator/winc.git
    private_key: {{CLOUDFOUNDRYINCUBATOR_WINC_DEPLOY_KEY}}
# - name: wincni-develop
#   type: git
#   source:
#     branch: develop
#     uri: https://github.com/cloudfoundry/wincni.git
# - name: wincni-master
#   type: git
#   source:
#     branch: master
#     uri: git@github.com:cloudfoundry/wincni.git
#     private_key: {{CLOUDFOUNDRY_WINCNI_DEPLOY_KEY}}
- name: winc-release-develop
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry-incubator/winc-release.git
    private_key: {{CLOUDFOUNDRYINCUBATOR_WINC-RELEASE_DEPLOY_KEY}}
- name: winc-release-master
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry-incubator/winc-release.git
    private_key: {{CLOUDFOUNDRYINCUBATOR_WINC-RELEASE_DEPLOY_KEY}}
- name: winc-release-develop-mergedback
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry-incubator/winc-release.git
    private_key: {{CLOUDFOUNDRYINCUBATOR_WINC-RELEASE_DEPLOY_KEY}}
- name: garden-runc-release
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/garden-runc-release.git
# - name: cf-networking-release
#   type: git
#   source:
#     branch: develop
#     uri: https://github.com/cloudfoundry-incubator/cf-networking-release.git
- name: gats-fork
  type: git
  source:
    branch: fork-master
    uri: https://github.com/greenhouse-org/garden-integration-tests.git
- name: guardian-fork
  type: git
  source:
    branch: fork-master
    uri: https://github.com/greenhouse-org/guardian.git
- name: pesto-garden-winc-deployment
  type: bosh-deployment
  source:
    deployment: garden-winc
    target: {{PESTO_BOSH_ENVIRONMENT}}
    client: {{PESTO_BOSH_CLIENT}}
    client_secret: {{PESTO_BOSH_CLIENT_SECRET}}
    ca_cert: {{PESTO_BOSH_CA_CERT}}
- name: stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells-release-candidates
    regexp: light-bosh-stemcell-(.*)-google-kvm-windows2016-go_agent.tgz
- name: pesto-lock-pool
  type: pool
  source:
    branch: master
    pool: pesto
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks
- name: every-2hrs
  type: time
  source:
    interval: 2h
- name: version
  type: semver
  source:
    access_key_id: {{BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY}}
    bucket: winc-release
    initial_version: 0.0.0
    key: version
    region_name: us-east-1
- name: winc-release-github-release
  type: github-release
  source:
    user: cloudfoundry-incubator
    repository: winc-release
    drafts: true
    access_token: {{GREENHOUSE_CI_ACCESS_TOKEN}}
jobs:
- name: winc
  serial: true
  serial_groups: [window2016]
  plan:
  - aggregate:
    - get: ci
    - get: every-2hrs
      trigger: true
    - get: winc-develop
      trigger: true
    - get: winc-master
  - task: test
    input_mapping: { winc: winc-develop }
    file: ci/test-winc/task.yml
  - task: merge-develop-to-master
    input_mapping: { from-repo: winc-develop, to-repo: winc-master }
    file: ci/merge-repo/task.yml
    params: { FROM_BRANCH: develop }
  - put: winc-master
    params: { repository: merged-repo/to-repo }

# - name: wincni
#   serial: true
#   plan:
#   - aggregate:
#     - get: ci
#     - get: every-2hrs
#       trigger: true
#     - get: wincni-develop
#       trigger: true
#     - get: wincni-master
#   - task: test
#     input_mapping: { wincni: wincni-develop }
#     file: ci/test-wincni/task.yml
#   - task: merge-develop-to-master
#     input_mapping: { from-repo: wincni-develop, to-repo: wincni-master }
#     file: ci/merge-repo/task.yml
#     params: { FROM_BRANCH: develop }
#   - put: wincni-master
#     params: { repository: merged-repo/to-repo }

# - name: wincni-smoke
#   serial: true
#   serial_groups: [window2016]
#   plan:
#   - aggregate:
#     - get: ci
#     - get: wincni-master
#       trigger: true
#       passed: [wincni]
#     - get: cf-networking-release
#   - task: build-wincni
#     file: ci/build-binary/task.yml
#     input_mapping:
#       repo: wincni-master
#     output_mapping:
#       binary-output: wincni-binary
#     params:
#       IMPORT_PATH: "code.cloudfoundry.org/wincni"
#       PACKAGE: "./cmd/wincni"
#   - task: wincni-smoke-test
#     file: ci/wincni-smoke/task.yml

- name: local-gats
  serial: true
  serial_groups: [window2016]
  plan:
  - aggregate:
    - get: ci
    - get: every-2hrs
      trigger: true
    - get: gats-fork
    - get: guardian-fork
    - get: garden-runc-release
    - get: winc-master
      passed: [winc]
      trigger: true
    - get: winc-release-develop
  - aggregate:
    - task: build-winc
      file: ci/build-binary/task.yml
      input_mapping:
        repo: winc-master
      output_mapping:
        binary-output: winc-binary
      params:
        IMPORT_PATH: "code.cloudfoundry.org/winc"
        PACKAGE: "./cmd/winc"
    - task: build-winc-network
      file: ci/build-binary/task.yml
      input_mapping:
        repo: winc-master
      output_mapping:
        binary-output: winc-network-binary
      params:
        IMPORT_PATH: "code.cloudfoundry.org/winc"
        PACKAGE: "./cmd/winc-network"
    - task: build-winc-image
      file: ci/build-binary/task.yml
      input_mapping:
        repo: winc-master
      output_mapping:
        binary-output: winc-image-binary
      params:
        IMPORT_PATH: "code.cloudfoundry.org/winc"
        PACKAGE: "./cmd/winc-image"
    - task: build-nstar
      file: ci/build-binary/task.yml
      input_mapping:
        repo: winc-release-develop
      output_mapping:
        binary-output: nstar-binary
      params:
        PACKAGE: "./src/nstar"
  - task: copy-forks
    file: ci/copy-forks/task.yml
    input_mapping:
      garden-integration-tests: gats-fork
      guardian: guardian-fork
  - task: run-gats
    file: ci/run-local-gats/task.yml

- name: bump-winc-release
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: winc-release-develop
    - get: winc-master
      passed:
      - local-gats
      trigger: true
  - task: bump-submodule
    file: ci/bump-submodule/task.yml
    params:
      SUBMODULE: "src/code.cloudfoundry.org/winc"
    input_mapping:
      source-repo: winc-release-develop
      module-repo: winc-master
  - put: winc-release-develop
    params:
      repository: bumped-repo
      rebase: true

- name: test-nstar
  plan:
  - aggregate:
    - get: ci
    - get: winc-release-develop
      trigger: true
  - task: run-ginkgo-exe
    file: ci/run-ginkgo-exe/task.yml
    input_mapping:
      repo: winc-release-develop
    params:
      TEST_PATH: "src/nstar"

- name: pesto-garden-winc-deploy
  serial: true
  plan:
  - put: pesto-lock-pool
    params:
      acquire: true
  - aggregate:
    - get: ci
    - get: stemcell
    - get: garden-runc-release
    - get: winc-release-develop
      passed: [test-nstar]
      trigger: true
  - task: create-winc-release
    file: ci/bosh-cr/task.yml
    input_mapping:
      release: winc-release-develop
    output_mapping:
      release-tarball: winc-tarball
  - task: open-garden-port
    file: ci/open-garden-port/task.yml
  - task: create-garden-runc-release
    file: ci/bosh-cr/task.yml
    input_mapping:
      release: garden-runc-release-open-port
    output_mapping:
      release-tarball: garden-runc-tarball
  - task: bosh-cleanup
    file: ci/bosh-cleanup/task.yml
    params:
      BOSH_CA_CERT: {{PESTO_BOSH_CA_CERT}}
      BOSH_CLIENT: {{PESTO_BOSH_CLIENT}}
      BOSH_CLIENT_SECRET: {{PESTO_BOSH_CLIENT_SECRET}}
      BOSH_ENVIRONMENT: {{PESTO_BOSH_ENVIRONMENT}}
  - put: pesto-garden-winc-deployment
    params:
      manifest: ci/garden-winc-manifest/manifest.yml
      stemcells:
      - stemcell/*.tgz
      releases:
      - winc-tarball/*.tgz
      - garden-runc-tarball/*.tgz
      cleanup: true
    on_failure:
      task: delete-deployment
      file: ci/bosh-deld/task.yml
      params:
        BOSH_CA_CERT: {{PESTO_BOSH_CA_CERT}}
        BOSH_CLIENT: {{PESTO_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{PESTO_BOSH_CLIENT_SECRET}}
        BOSH_DEPLOYMENT: garden-winc
        BOSH_ENVIRONMENT: {{PESTO_BOSH_ENVIRONMENT}}
  ensure:
    put: pesto-lock-pool
    params:
      release: pesto-lock-pool

- name: pesto-gats
  serial: true
  plan:
  - put: pesto-lock-pool
    params:
      acquire: true
  - aggregate:
    - get: ci
    - get: winc-release-develop
      passed: [pesto-garden-winc-deploy]
      trigger: true
    - get: garden-runc-release
      passed: [pesto-garden-winc-deploy]
    - get: garden-integration-tests
      resource: gats-fork
  - task: run-gats
    file: ci/run-remote-gats/task.yml
    input_mapping:
    params:
      GARDEN_ADDRESS: 35.185.94.204
      GARDEN_PORT: 7777
    on_success:
      task: delete-deployment
      file: ci/bosh-deld/task.yml
      params:
        BOSH_CA_CERT: {{PESTO_BOSH_CA_CERT}}
        BOSH_CLIENT: {{PESTO_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{PESTO_BOSH_CLIENT_SECRET}}
        BOSH_DEPLOYMENT: garden-winc
        BOSH_ENVIRONMENT: {{PESTO_BOSH_ENVIRONMENT}}
  ensure:
    put: pesto-lock-pool
    params:
      release: pesto-lock-pool

- name: shipit
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: winc-release-develop
      passed: [pesto-gats]
    - get: winc-release-master
    - get: version
      params: {bump: minor}
  - task: merge-develop-to-master
    input_mapping: { from-repo: winc-release-develop, to-repo: winc-release-master }
    file: ci/merge-repo/task.yml
    params: { FROM_BRANCH: develop }
  - put: version
    params: {file: version/number}
  - task: finalize-release
    file: ci/finalize-release/task.yml
    input_mapping: { release: winc-release-master }
    params:
      RELEASE_NAME: winc
      AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
  - put: winc-release-master
    params:
      repository: finalized-release/release
      tag: version/number
      tag_prefix: v
  - task: generate-release
    input_mapping: { release: winc-release-master }
    file: ci/generate-github-release/task.yml
  - put: winc-release-github-release
    params:
      commitish: generated-release/commitish
      name: generated-release/name
      tag: generated-release/version
      globs:
      - finalized-release/winc-*.tgz
- name: merge-master-into-develop
  plan:
    - aggregate:
      - get: ci
      - get: from-repo
        resource: winc-release-master
        trigger: true
        passed: [shipit]
        params:
          submodules: none
      - get: to-repo
        resource: winc-release-develop
        params:
          submodules: none
    - task: merge-master-into-develop
      file: ci/merge-repo/task.yml
      params:
        FROM_BRANCH: master
    - put: winc-release-develop-mergedback
      params:
        repository: merged-repo/to-repo
groups:
- name: winc
  jobs:
  - winc
  - local-gats
  - bump-winc-release
- name: winc-release
  jobs:
  - test-nstar
  - pesto-garden-winc-deploy
  - pesto-gats
  - shipit
  - merge-master-into-develop
# - name: wincni
#   jobs:
#   - wincni
#   - wincni-smoke
