resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: winc-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry-incubator/winc.git
- name: winc-master
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry-incubator/winc.git
    private_key: {{CLOUDFOUNDRYINCUBATOR_WINC_DEPLOY_KEY}}
- name: winc-release-develop
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry-incubator/winc-release.git
    private_key: {{CLOUDFOUNDRYINCUBATOR_WINC-RELEASE_DEPLOY_KEY}}
- name: garden-runc-release
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/garden-runc-release.git
- name: gats-fork
  type: git
  source:
    branch: master
    uri: https://github.com/greenhouse-org/garden-integration-tests.git
- name: guardian-fork
  type: git
  source:
    branch: master
    uri: https://github.com/greenhouse-org/guardian.git
- name: pesto-garden-winc-deployment
  type: bosh-deployment
  source:
    deployment: garden-winc
    target: {{PESTO_BOSH_ENVIRONMENT}}
    client: {{PESTO_BOSH_CLIENT}}
    client_secret: {{PESTO_BOSH_CLIENT_SECRET}}
    ca_cert: {{PESTO_BOSH_CA_CERT}}
- name: stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells-release-candidates
    regexp: light-bosh-stemcell-(.*)-google-kvm-windows2016-go_agent.tgz
- name: pesto-lock-pool
  type: pool
  source:
    branch: master
    pool: pesto
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks
- name: every-2hrs
  type: time
  source:
    interval: 2h

jobs:
- name: winc
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: every-2hrs
      trigger: true
    - get: winc-develop
      trigger: true
    - get: winc-master
  - task: test
    tags: [windows2016]
    input_mapping: { winc: winc-develop }
    file: ci/test-winc/task.yml
  - task: merge-develop-to-master
    input_mapping: { from-repo: winc-develop, to-repo: winc-master }
    file: ci/merge-repo/task.yml
    params: { FROM_BRANCH: develop }
  - put: winc-master
    params: { repository: merged-repo/to-repo }

- name: local-gats
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: every-2hrs
      trigger: true
    - get: gats-fork
    - get: guardian-fork
    - get: garden-runc-release
    - get: winc-master
      passed: [winc]
      trigger: true
  - task: build-winc
    file: ci/build-winc/task.yml
    input_mapping:
      winc: winc-master
    tags: [windows2016]
  - task: run-gats
    file: ci/run-local-gats/task.yml
    input_mapping:
      garden-integration-tests: gats-fork
      guardian: guardian-fork
    tags: [windows2016]

- name: bump-winc-release
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: winc-release-develop
    - get: winc-master
      passed:
      - local-gats
      trigger: true
  - task: bump-submodule
    file: ci/bump-submodule/task.yml
    params:
      SUBMODULE: "src/code.cloudfoundry.org/winc"
    input_mapping:
      source-repo: winc-release-develop
      module-repo: winc-master
  - put: winc-release-develop
    params:
      repository: bumped-repo
      rebase: true

- name: pesto-garden-winc-deploy
  serial: true
  plan:
  - put: pesto-lock-pool
    params:
      acquire: true
  - aggregate:
    - get: ci
    - get: stemcell
    - get: garden-runc-release
    - get: winc-release-develop
      passed: [bump-winc-release]
      trigger: true
  - task: create-winc-release
    file: ci/bosh-cr/task.yml
    input_mapping:
      release: winc-release-develop
    output_mapping:
      release-tarball: winc-tarball
  - task: open-garden-port
    file: ci/open-garden-port/task.yml
  - task: create-garden-runc-release
    file: ci/bosh-cr/task.yml
    input_mapping:
      release: garden-runc-release-open-port
    output_mapping:
      release-tarball: garden-runc-tarball
  - task: bosh-cleanup
    file: ci/bosh-cleanup/task.yml
    params:
      BOSH_CA_CERT: {{PESTO_BOSH_CA_CERT}}
      BOSH_CLIENT: {{PESTO_BOSH_CLIENT}}
      BOSH_CLIENT_SECRET: {{PESTO_BOSH_CLIENT_SECRET}}
      BOSH_ENVIRONMENT: {{PESTO_BOSH_ENVIRONMENT}}
  - put: pesto-garden-winc-deployment
    params:
      manifest: ci/garden-winc-manifest/manifest.yml
      stemcells:
      - stemcell/*.tgz
      releases:
      - winc-tarball/*.tgz
      - garden-runc-tarball/*.tgz
      cleanup: true

- name: pesto-gats
  serial: true
  plan:
  - get: pesto-lock-pool
    passed: [pesto-garden-winc-deploy]
    trigger: true
  - aggregate:
    - get: ci
    - get: winc-release-develop
      passed: [pesto-garden-winc-deploy]
    - get: garden-runc-release
      passed: [pesto-garden-winc-deploy]
    - get: garden-integration-tests
      resource: gats-fork
  - task: run-gats
    file: ci/run-remote-gats/task.yml
    input_mapping:
    params:
      GARDEN_ADDRESS: 35.185.94.204
      GARDEN_PORT: 7777
    on_success:
      task: delete-deployment
      file: ci/bosh-deld/task.yml
      params:
        BOSH_CA_CERT: {{PESTO_BOSH_CA_CERT}}
        BOSH_CLIENT: {{PESTO_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{PESTO_BOSH_CLIENT_SECRET}}
        BOSH_DEPLOYMENT: garden-winc
        BOSH_ENVIRONMENT: {{PESTO_BOSH_ENVIRONMENT}}
  ensure:
    put: pesto-lock-pool
    params:
      release: pesto-lock-pool
