resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: windows2016fs-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/windows2016fs-release.git
- name: git-setup
  type: github-release
  source:
    user: git-for-windows
    repository: git
- name: tar
  type: s3
  source:
    bucket: bosh-windows-dependencies
    regexp: tar-(.*).exe
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: version
  type: semver
  source:
    access_key_id: {{BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY}}
    bucket: windows2016fs
    initial_version: 0.0.0
    key: version
    region_name: us-east-1

jobs:
- name: build-and-push
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: windows2016fs-release
      trigger: true
    - get: git-setup
      trigger: true
      params:
        globs: [Git-*-64-bit.exe]
    - get: tar
      trigger: true
    - get: version
    - put: version
      params: {bump: patch}
  - task: build-urlacl
    file: ci/build-binary/task.yml
    input_mapping:
      repo: windows2016fs-release
    output_mapping:
      binary-output: urlacl
    params:
      PACKAGE: "./src/urlacl"
  - task: build-and-push
    file: ci/docker-build-and-push/task.yml
    input_mapping:
      repo: windows2016fs-release
    params:
      DOCKERFILE: repo/src/Dockerfile
      IMAGE_NAME: cloudfoundry/windows2016fs
      DOCKER_USERNAME: {{DOCKER_USERNAME}}
      DOCKER_PASSWORD: {{DOCKER_PASSWORD}}
