---
platform: linux

image_resource: {type: docker-image, source: {repository: cloudfoundry/garden-windows-ci}}

inputs:
- name: ci
- name: release-tarball

outputs:
- name: windows2016fs-opsfile

run:
  path: ci/tasks/write-windows2016fs-opsfile/run
