---
name: garden-winc

releases:
- name: winc
  version: latest
- name: garden-runc
  version: latest

stemcells:
- alias: windows
  os: windows2016
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000-300000
  max_errors: 2
  max_in_flight: 1
  serial: false
  update_watch_time: 30000-300000

instance_groups:
- azs:
  - z1
  name: garden-windows
  instances: 1
  jobs:
  - name: winc
    release: winc
  - name: winc-image
    release: winc
  - name: winc-network
    release: winc
  - name: garden-windows
    properties:
      garden:
        listen_address: "0.0.0.0:7777"
        image_plugin: "/var/vcap/packages/winc-image/winc-image.exe"
        runtime_plugin: "/var/vcap/packages/winc/winc.exe"
        network_plugin: "/var/vcap/packages/winc-network/winc-network.exe"
        nstar_bin: "/var/vcap/packages/nstar/nstar.exe"
        default_container_rootfs: "/var/vcap/packages/windows2016fs/rootfs"
        log_level: "debug"
    release: garden-runc
  networks:
  - name: default
    default:
    - dns
    - gateway
  - name: vip
    static_ips: [35.185.94.204]
  stemcell: windows
  vm_extensions:
  - 100GB_ephemeral_disk
  vm_type: m3.large
