---
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/garden-windows-ci

platform: linux

inputs:
- name: ci

params:
  CF_APP_URL:
  DATADOG_TAG:
  DATADOG_API_KEY:
  DATADOG_APPLICATION_KEY:

run:
  path: ci/tasks/curl-app/run
