---
platform: linux

image_resource: {type: docker-image, source: {repository: cloudfoundry/garden-windows-ci}}

inputs:
- name: ci
- name: windows2016fs
  path: src/code.cloudfoundry.org/windows2016fs

run:
  path: ci/tasks/test-windows2016fs-linux/run

params:
  IGNORE_PACKAGES:
