---
platform: windows

inputs:
- name: ci
- name: windows2016fs
  path: src/code.cloudfoundry.org/windows2016fs

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/test-windows2016fs-windows/run.ps1

params:
  NODES: 1
