---
image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/ci

platform: linux

inputs:
- name: ci

params:
  CF_API:
  CF_USERNAME:
  CF_PASSWORD:

run:
  path: ci/tasks/enable-credhub/run
