- name: Add Dell PPA
  when: is_ubuntu
  apt_repository: repo={{ item }}
  with_items:
    - 'deb http://dell.archive.canonical.com/updates/ trusty-dell-avalon-refresh public'
    - 'deb-src http://dell.archive.canonical.com/updates/ trusty-dell-avalon-refresh public'
    - 'deb http://dell.archive.canonical.com/updates/ trusty-dell-ws-vivid-skl public'
    - 'deb-src http://dell.archive.canonical.com/updates/ trusty-dell-ws-vivid-skl public'
    - 'deb http://dell.archive.canonical.com/updates/ trusty-dell public'
    - 'deb-src http://dell.archive.canonical.com/updates/ trusty-dell public'
    - 'deb http://dell.archive.canonical.com/updates/ xenial-dell public'
    - 'deb-src http://dell.archive.canonical.com/updates/ xenial-dell public'
    - 'deb http://dell.archive.canonical.com/updates/ xenial-oem public'
    - 'deb-src http://dell.archive.canonical.com/updates/ xenial-oem public'
