- name: Add freerdp PPA (linux)
  when: is_ubuntu
  apt_repository: repo='ppa:dlrsolstamp/freerdp'
- name: Install freerdp
  when: is_ubuntu
  package: name=freerdp-x11
- name: Install Chrome
  when: is_osx
  homebrew_cask: name=xquartz
  become: yes
  become_user: pivotal
- name: Install freerdp (osx)
  when: is_osx
  homebrew:
    name: freerdp
    state: present
    install_options: "--HEAD"
  become: yes
  become_user: pivotal
