- name: change perm for GOROOT
  when: is_ubuntu
  file:
    path: "/usr/local/src/go"
    owner: pivotal
    group: pivotal
    recurse: yes
- name: change perm for go
  when: is_ubuntu
  file:
    path: "/home/pivotal/go"
    owner: pivotal
    group: pivotal
    recurse: yes
