- name: Add Google Cloud SDK apt keys (linux)
  when: is_ubuntu
  apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg
- name: Add Google Cloud SDK PPA (linux)
  when: is_ubuntu
  apt_repository: repo='deb http://packages.cloud.google.com/apt cloud-sdk-{{ ansible_distribution_release }} main'
- name: Install Google Cloud SDK (linux)
  when: is_ubuntu
  package: name=google-cloud-sdk
- name: Install Google Cloud SDK (osx)
  when: is_osx
  homebrew_cask: name=google-cloud-sdk
  become: yes
  become_user: pivotal
