- name: Update Homebrew
  when: is_osx
  homebrew: update_homebrew=yes
  become: yes
  become_user: pivotal
- name: Add Homebrew taps
  when: is_osx
  homebrew_tap: tap={{ item }}
  with_items:
    - caskroom/cask
    - caskroom/fonts
    - caskroom/versions
  become: yes
  become_user: pivotal
