- name: Install lpass deps (linux)
  when: is_ubuntu
  package: name={{ item }}
  with_items:
    - openssl
    - libcurl4-openssl-dev
    - libxml2
    - libssl-dev
    - libxml2-dev
    - pinentry-curses
    - xclip
    - cmake
    - build-essential
    - pkg-config
- name: Download lastpass (linux)
  when: is_ubuntu
  git:
    repo: git://github.com/lastpass/lastpass-cli.git
    dest: "/usr/local/src/lpass"
    version: master
    update: yes
    accept_hostkey: yes
- name: Install lpass (linux)
  when: is_ubuntu
  make:
    chdir: "/usr/local/src/lpass"
    target: install
- name: Install lpass (osx)
  when: is_osx
  package: name=lastpass-cli
  become: yes
  become_user: pivotal
