- name: Install tmux deps (linux)
  when: is_ubuntu
  package: name={{ item }}
  with_items:
    - libevent-dev
    - libncurses-dev
- name: Create tmux dir (linux)
  when: is_ubuntu
  file:
    path: "/tmp/tmux"
    state: directory
    mode: 0755
- name: Download tmux (linux)
  when: is_ubuntu
  unarchive:
    src: "https://github.com/tmux/tmux/releases/download/2.6/tmux-2.6.tar.gz"
    dest: "/tmp/tmux"
    remote_src: yes
- name: Install tmux (linux)
  when: is_ubuntu
  shell: "./configure"
  args:
    chdir: "/tmp/tmux/tmux-2.6"
- name: Install tmux (linux)
  when: is_ubuntu
  make:
    chdir: "/tmp/tmux/tmux-2.6"
    target: install
- name: Install tmux (osx)
  when: is_osx
  package: name=tmux
  become: yes
  become_user: pivotal
- name: Setup tmux conf
  git:
    repo: git://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    version: master
    update: yes
    accept_hostkey: yes
  become: yes
  become_user: pivotal
