- name: Install vagrant cli (linux)
  when: is_ubuntu
  apt:
    deb: "https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.deb"
    state: present
- name: Install vagrant cli (osx)
  when: is_osx
  homebrew_cask: name=vagrant
  become: yes
  become_user: pivotal
