---
- name: Install workstation deps
  when: is_ubuntu
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - x11-apps
    - libxtst6
    - libxinerama1
    - libxi6
- name: Download workstation
  when: is_ubuntu
  get_url:
    url: "http://download3.vmware.com/software/wkst/file/VMware-Workstation-Full-12.5.9-7535481.x86_64.bundle"
    dest: "/tmp/vmware.bundle"
- name: Run installer
  when: is_ubuntu
  shell: >
    sh /tmp/vmware.bundle --eulas-agreed --console --required
  args:
    creates: /usr/bin/vmware
  become: yes
