---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: ci
  - name: version
  - name: windows2016fs-release
  - name: create-windows-sha
  - name: create-linux-sha

outputs:
  - name: windows2016fs-release-updated-version

run:
  path: ci/tasks/update-fs-release-version/run

